image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      yes 2>/dev/null | sdkmanager "platform-tools" "platforms;android-29" &&
      ./gradlew build
    command: |
      if [[ -z "$APPETIZE_API_TOKEN" ]]; then
          echo "Appetize API token not set. Run:"
          echo "    gp env APPETIZE_API_TOKEN=your_token"
          echo "and restart this workspace in order to get an app preview."
          echo "Request your token here: https://appetize.io/docs#request-api-token"
      else
          curl -sS --http1.1 "https://$APPETIZE_API_TOKEN@api.appetize.io/v1/apps/$APPETIZE_PUBLICKEY" \
              -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
              -F platform=android \
              -F "buttonText=Start App" \
              -F "postSessionButtonText=Start App" \
              > .appetize.json
          APPETIZE_PUBLICKEY=$(jq -r .publicKey .appetize.json)
          export APPETIZE_PUBLICKEY
          echo "export APPETIZE_PUBLICKEY=$APPETIZE_PUBLICKEY" >> ~/.bashrc
          gp env "APPETIZE_PUBLICKEY=$APPETIZE_PUBLICKEY"
          python -m webbrowser "https://appetize.io/embed/$APPETIZE_PUBLICKEY?device=pixel4&autoplay=true"
      fi
